
namespace GestionEquestre.Ge {
    export interface PersonneRow {
        Id?: string;
        IsMorale?: boolean;
        IsActive?: boolean;
        NotArchive?: boolean;
        InsertDate?: string;
        InsertUserId?: number;
        UpdateDate?: string;
        UpdateUserId?: number;
        Nom?: string;
        Prenom?: string;
        NomJeuneFille?: string;
        RaisonSociale?: string;
        Birthday?: string;
        Sexe?: number;
        SituationFamille?: number;
        VilleNassance?: string;
        PaysNassance?: string;
        PaysNationalite?: string;
        Photo?: number[];
        TelephonePerso?: string;
        TelephoneMobile?: string;
        TelephoneProf?: string;
        TelephoneComplementaire1?: string;
        TelephoneComplementaire2?: string;
        Email1?: string;
        Email2?: string;
        CompteBancaire?: string;
        IdAdresse?: string;
        Description?: string;
        ArchiveDate?: string;
        SexeDefaultValue?: boolean;
        SexeIsActive?: boolean;
        SexeReadOnly?: boolean;
        SexeInsertDate?: string;
        SexeInsertUserId?: number;
        SexeUpdateDate?: string;
        SexeUpdateUserId?: number;
        SexeLibele?: string;
        SexeCivilite?: string;
        SexeLibeleUs?: string;
        SituationFamilleDefaultValue?: boolean;
        SituationFamilleIsActive?: boolean;
        SituationFamilleReadOnly?: boolean;
        SituationFamilleInsertDate?: string;
        SituationFamilleInsertUserId?: number;
        SituationFamilleUpdateDate?: string;
        SituationFamilleUpdateUserId?: number;
        SituationFamilleLibele?: string;
        SituationFamilleCode?: string;
        VilleNassanceDefaultValue?: boolean;
        VilleNassanceIsActive?: boolean;
        VilleNassanceReadOnly?: boolean;
        VilleNassanceInsertDate?: string;
        VilleNassanceInsertUserId?: number;
        VilleNassanceUpdateDate?: string;
        VilleNassanceUpdateUserId?: number;
        VilleNassanceCodeInsee?: string;
        VilleNassanceLibele?: string;
        VilleNassanceNomVille?: string;
        VilleNassanceCodePostal?: string;
        VilleNassancePays?: string;
        PaysNassanceDefaultValue?: boolean;
        PaysNassanceIsActive?: boolean;
        PaysNassanceReadOnly?: boolean;
        PaysNassanceInsertDate?: string;
        PaysNassanceInsertUserId?: number;
        PaysNassanceUpdateDate?: string;
        PaysNassanceUpdateUserId?: number;
        PaysNassanceLibele?: string;
        PaysNassanceCode?: string;
        PaysNassanceCodeUe?: number;
        PaysNationaliteDefaultValue?: boolean;
        PaysNationaliteIsActive?: boolean;
        PaysNationaliteReadOnly?: boolean;
        PaysNationaliteInsertDate?: string;
        PaysNationaliteInsertUserId?: number;
        PaysNationaliteUpdateDate?: string;
        PaysNationaliteUpdateUserId?: number;
        PaysNationaliteLibele?: string;
        PaysNationaliteCode?: string;
        PaysNationaliteCodeUe?: number;
        CompteBancaireCodePaysIban?: string;
        CompteBancaireCleIban?: string;
        CompteBancaireBanque?: string;
        CompteBancaireGuichet?: string;
        CompteBancaireNumeroCompte?: string;
        CompteBancaireCleRib?: string;
        CompteBancaireEmetteurRib?: string;
        CompteBancaireBic?: string;
        CompteBancaireTitulaireCompte?: string;
        CompteBancaireDomiciliation?: string;
        CompteBancaireCodeIcs?: string;
        CompteBancaireCodeRum?: string;
        CompteBancaireDateSignatureMandat?: string;
        CompteBancaireTypePrelevement?: number;
        CompteBancaireDateDernierPrelevement?: string;
        CompteBancaireTypeDernierPrelevement?: number;
        IdAdresseIsActive?: boolean;
        IdAdresseNotArchive?: boolean;
        IdAdresseInsertDate?: string;
        IdAdresseInsertUserId?: number;
        IdAdresseUpdateDate?: string;
        IdAdresseUpdateUserId?: number;
        IdAdresseAdresse1?: string;
        IdAdresseAdresse2?: string;
        IdAdresseAdresse3?: string;
        IdAdresseVille?: string;
        IdAdressePays?: string;
        IdAdresseCedex?: string;
        IdAdresseBatiment?: string;
        IdAdresseDescription?: string;
        IdAdresseArchiveDate?: string;
    }

    export namespace PersonneRow {
        export const idProperty = 'Id';
        export const nameProperty = 'Nom';
        export const localTextPrefix = 'Ge.Personne';

        export namespace Fields {
            export declare const Id;
            export declare const IsMorale;
            export declare const IsActive;
            export declare const NotArchive;
            export declare const InsertDate;
            export declare const InsertUserId;
            export declare const UpdateDate;
            export declare const UpdateUserId;
            export declare const Nom;
            export declare const Prenom;
            export declare const NomJeuneFille;
            export declare const RaisonSociale;
            export declare const Birthday;
            export declare const Sexe;
            export declare const SituationFamille;
            export declare const VilleNassance;
            export declare const PaysNassance;
            export declare const PaysNationalite;
            export declare const Photo;
            export declare const TelephonePerso;
            export declare const TelephoneMobile;
            export declare const TelephoneProf;
            export declare const TelephoneComplementaire1;
            export declare const TelephoneComplementaire2;
            export declare const Email1;
            export declare const Email2;
            export declare const CompteBancaire;
            export declare const IdAdresse;
            export declare const Description;
            export declare const ArchiveDate;
            export declare const SexeDefaultValue: string;
            export declare const SexeIsActive: string;
            export declare const SexeReadOnly: string;
            export declare const SexeInsertDate: string;
            export declare const SexeInsertUserId: string;
            export declare const SexeUpdateDate: string;
            export declare const SexeUpdateUserId: string;
            export declare const SexeLibele: string;
            export declare const SexeCivilite: string;
            export declare const SexeLibeleUs: string;
            export declare const SituationFamilleDefaultValue: string;
            export declare const SituationFamilleIsActive: string;
            export declare const SituationFamilleReadOnly: string;
            export declare const SituationFamilleInsertDate: string;
            export declare const SituationFamilleInsertUserId: string;
            export declare const SituationFamilleUpdateDate: string;
            export declare const SituationFamilleUpdateUserId: string;
            export declare const SituationFamilleLibele: string;
            export declare const SituationFamilleCode: string;
            export declare const VilleNassanceDefaultValue: string;
            export declare const VilleNassanceIsActive: string;
            export declare const VilleNassanceReadOnly: string;
            export declare const VilleNassanceInsertDate: string;
            export declare const VilleNassanceInsertUserId: string;
            export declare const VilleNassanceUpdateDate: string;
            export declare const VilleNassanceUpdateUserId: string;
            export declare const VilleNassanceCodeInsee: string;
            export declare const VilleNassanceLibele: string;
            export declare const VilleNassanceNomVille: string;
            export declare const VilleNassanceCodePostal: string;
            export declare const VilleNassancePays: string;
            export declare const PaysNassanceDefaultValue: string;
            export declare const PaysNassanceIsActive: string;
            export declare const PaysNassanceReadOnly: string;
            export declare const PaysNassanceInsertDate: string;
            export declare const PaysNassanceInsertUserId: string;
            export declare const PaysNassanceUpdateDate: string;
            export declare const PaysNassanceUpdateUserId: string;
            export declare const PaysNassanceLibele: string;
            export declare const PaysNassanceCode: string;
            export declare const PaysNassanceCodeUe: string;
            export declare const PaysNationaliteDefaultValue: string;
            export declare const PaysNationaliteIsActive: string;
            export declare const PaysNationaliteReadOnly: string;
            export declare const PaysNationaliteInsertDate: string;
            export declare const PaysNationaliteInsertUserId: string;
            export declare const PaysNationaliteUpdateDate: string;
            export declare const PaysNationaliteUpdateUserId: string;
            export declare const PaysNationaliteLibele: string;
            export declare const PaysNationaliteCode: string;
            export declare const PaysNationaliteCodeUe: string;
            export declare const CompteBancaireCodePaysIban: string;
            export declare const CompteBancaireCleIban: string;
            export declare const CompteBancaireBanque: string;
            export declare const CompteBancaireGuichet: string;
            export declare const CompteBancaireNumeroCompte: string;
            export declare const CompteBancaireCleRib: string;
            export declare const CompteBancaireEmetteurRib: string;
            export declare const CompteBancaireBic: string;
            export declare const CompteBancaireTitulaireCompte: string;
            export declare const CompteBancaireDomiciliation: string;
            export declare const CompteBancaireCodeIcs: string;
            export declare const CompteBancaireCodeRum: string;
            export declare const CompteBancaireDateSignatureMandat: string;
            export declare const CompteBancaireTypePrelevement: string;
            export declare const CompteBancaireDateDernierPrelevement: string;
            export declare const CompteBancaireTypeDernierPrelevement: string;
            export declare const IdAdresseIsActive: string;
            export declare const IdAdresseNotArchive: string;
            export declare const IdAdresseInsertDate: string;
            export declare const IdAdresseInsertUserId: string;
            export declare const IdAdresseUpdateDate: string;
            export declare const IdAdresseUpdateUserId: string;
            export declare const IdAdresseAdresse1: string;
            export declare const IdAdresseAdresse2: string;
            export declare const IdAdresseAdresse3: string;
            export declare const IdAdresseVille: string;
            export declare const IdAdressePays: string;
            export declare const IdAdresseCedex: string;
            export declare const IdAdresseBatiment: string;
            export declare const IdAdresseDescription: string;
            export declare const IdAdresseArchiveDate: string;
        }

        ['Id', 'IsMorale', 'IsActive', 'NotArchive', 'InsertDate', 'InsertUserId', 'UpdateDate', 'UpdateUserId', 'Nom', 'Prenom', 'NomJeuneFille', 'RaisonSociale', 'Birthday', 'Sexe', 'SituationFamille', 'VilleNassance', 'PaysNassance', 'PaysNationalite', 'Photo', 'TelephonePerso', 'TelephoneMobile', 'TelephoneProf', 'TelephoneComplementaire1', 'TelephoneComplementaire2', 'Email1', 'Email2', 'CompteBancaire', 'IdAdresse', 'Description', 'ArchiveDate', 'SexeDefaultValue', 'SexeIsActive', 'SexeReadOnly', 'SexeInsertDate', 'SexeInsertUserId', 'SexeUpdateDate', 'SexeUpdateUserId', 'SexeLibele', 'SexeCivilite', 'SexeLibeleUs', 'SituationFamilleDefaultValue', 'SituationFamilleIsActive', 'SituationFamilleReadOnly', 'SituationFamilleInsertDate', 'SituationFamilleInsertUserId', 'SituationFamilleUpdateDate', 'SituationFamilleUpdateUserId', 'SituationFamilleLibele', 'SituationFamilleCode', 'VilleNassanceDefaultValue', 'VilleNassanceIsActive', 'VilleNassanceReadOnly', 'VilleNassanceInsertDate', 'VilleNassanceInsertUserId', 'VilleNassanceUpdateDate', 'VilleNassanceUpdateUserId', 'VilleNassanceCodeInsee', 'VilleNassanceLibele', 'VilleNassanceNomVille', 'VilleNassanceCodePostal', 'VilleNassancePays', 'PaysNassanceDefaultValue', 'PaysNassanceIsActive', 'PaysNassanceReadOnly', 'PaysNassanceInsertDate', 'PaysNassanceInsertUserId', 'PaysNassanceUpdateDate', 'PaysNassanceUpdateUserId', 'PaysNassanceLibele', 'PaysNassanceCode', 'PaysNassanceCodeUe', 'PaysNationaliteDefaultValue', 'PaysNationaliteIsActive', 'PaysNationaliteReadOnly', 'PaysNationaliteInsertDate', 'PaysNationaliteInsertUserId', 'PaysNationaliteUpdateDate', 'PaysNationaliteUpdateUserId', 'PaysNationaliteLibele', 'PaysNationaliteCode', 'PaysNationaliteCodeUe', 'CompteBancaireCodePaysIban', 'CompteBancaireCleIban', 'CompteBancaireBanque', 'CompteBancaireGuichet', 'CompteBancaireNumeroCompte', 'CompteBancaireCleRib', 'CompteBancaireEmetteurRib', 'CompteBancaireBic', 'CompteBancaireTitulaireCompte', 'CompteBancaireDomiciliation', 'CompteBancaireCodeIcs', 'CompteBancaireCodeRum', 'CompteBancaireDateSignatureMandat', 'CompteBancaireTypePrelevement', 'CompteBancaireDateDernierPrelevement', 'CompteBancaireTypeDernierPrelevement', 'IdAdresseIsActive', 'IdAdresseNotArchive', 'IdAdresseInsertDate', 'IdAdresseInsertUserId', 'IdAdresseUpdateDate', 'IdAdresseUpdateUserId', 'IdAdresseAdresse1', 'IdAdresseAdresse2', 'IdAdresseAdresse3', 'IdAdresseVille', 'IdAdressePays', 'IdAdresseCedex', 'IdAdresseBatiment', 'IdAdresseDescription', 'IdAdresseArchiveDate'].forEach(x => (<any>Fields)[x] = x);
    }
}

