using Serenity.Navigation;
using MyPages = GestionEquestre.Ge.Pages;

[assembly: NavigationLink(int.MaxValue, "Ge/Acc Bankaccount", typeof(MyPages.AccBankaccountController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Man Adress", typeof(MyPages.ManAdressController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Man Cavaliers", typeof(MyPages.ManCavaliersController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Man Owner", typeof(MyPages.ManOwnerController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Man Person", typeof(MyPages.ManPersonController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Set City", typeof(MyPages.SetCityController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Set Country", typeof(MyPages.SetCountryController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Set Galop", typeof(MyPages.SetGalopController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Set Lfc", typeof(MyPages.SetLfcController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Set Maritalstatus", typeof(MyPages.SetMaritalstatusController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Set Sexe", typeof(MyPages.SetSexeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Set Uelnorga", typeof(MyPages.SetUelnorgaController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Man Horses", typeof(MyPages.ManHorsesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Link Folder Cavalier", typeof(MyPages.LinkFolderCavalierController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Link Folder Horse", typeof(MyPages.LinkFolderHorseController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Link Folder Person", typeof(MyPages.LinkFolderPersonController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Ge/Man Folder", typeof(MyPages.ManFolderController), icon: null)]